version: '3.8'
services:
  a:
    image: alpine
    command: ["ping" , "google.fr"]
  b:
    env_file:
      - .env
    environment:
      - NODE_ENV # Read data from .env file
    build: 
      context : .
      dockerfile : Dockerfile
      args :
        - FOLDER=test2
      labels :
        - Email=mirhzeranas@gmail.com
    ports:
      - 8082:8082
    volumes:
      - type : bind
        source: ./data
        target: /app/data
      - type: volume
        source: datavolume
        target: /app/datavolume
    command: ["ping" , "google.fr"]
    links: 
      - "a:myAlias" # create alias for container network

volumes:
  datavolume:
    external: false # fail if external volume not present/created